CREATE DATABASE SCHOOLAPP;

USE SCHOOLAPP;

CREATE TABLE SUBJECTS(
	ID				BIGINT IDENTITY NOT NULL,
	SUBJECT_NAME	VARCHAR(30) NOT NULL,
	SEMESTER		INT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE STUDENT(
	ID			BIGINT IDENTITY NOT NULL,
	FIRST_NAME	VARCHAR(20) NOT NULL,
	LAST_NAME	VARCHAR(20) NOT NULL,
	SUBJECT_ID	BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TEACHERS(
	ID			BIGINT IDENTITY NOT NULL,
	FIRST_NAME	VARCHAR(20) NOT NULL,
	LAST_NAME	VARCHAR(20) NOT NULL,
	SUBJECT_ID	BIGINT NOT NULL,
	PRIMARY KEY(ID)
);


ALTER TABLE STUDENT ADD CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);
ALTER TABLE TEACHERS ADD CONSTRAINT FK_SUBJECT_TEACHERS FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

